### PR TITLE
fix: For window is not defined error in the theme preference

### PR DESCRIPTION
**Pull request by Danziger**

### CODE REVIEW

**Comment by pawanpaudel93** [comment]
@Danziger Now the service worker is working fine. Still, there is another issue I noticed: Now if you use the injected api, all the popups are either full white or black based on the theme. You could just try to connect wallet to any of the dapps to reproduce the issue.

**Comment by Danziger** [comment]
@pawanpaudel93 It should be fine now, just tested it on Bazar.

**Review by 7i7o — APPROVED** [review]
tACK 👍

**Review by pawanpaudel93 — APPROVED** [review]
tACK 🚀

**Pull request merged**
