### PR TITLE
feat: ArConnect Notifications when receiving or sending AR

### PR DESCRIPTION
**Pull request by nicholaswma**
- Initializes an alarm on install to trigger every minute
- this currently only pulls notifications for the active address
- Pulls recipient and owner queries and filters for transfer of AR
- Adds a setting for Notifications

### CODE REVIEW

**Review by elehma4 — APPROVED** [review]
tACK 👍🏼  note: make sure system notifications are toggled on

**Review by 7i7o — APPROVED** [review]
tACK 🚀

**Review by 7i7o — APPROVED** [review]
LGTM 🚀

**Comment by nicholaswma** [comment]
combining with https://github.com/arconnectio/ArConnect/pull/246

**Pull request closed without merging**
