### PR TITLE
feat: add Ledger wallet integration

### PR DESCRIPTION
**Pull request by CDDelta**
This PR adds support for connecting ArConnect to a Ledger with an Arweave wallet.

Note:
- Multiple Ledger wallets can be added but only one may be active (connected to the browser) at once.
- If the active wallet in ArConnect does not match the one on the connected Ledger an error is thrown.
- Config exports exclude Ledger wallet records.
- Due to limitations with the Ledger x Arweave API, encryption/decryption and custom signature requests resolve with an "Action not supported" error when called.
- Transaction signing requests to a Ledger will error if provided with custom signature options.

### CODE REVIEW

**Comment by CDDelta** [comment]
Blocked on some typings issue with the [Ledger SDK](https://github.com/Zondax/ledger-arweave/pull/43). We could potentially release with our own fork release of the SDK if needed.

**Comment by martonlederer** [comment]
Is this ready to merge or should I merge the other one? I believe that also has the ledger stuff

**Comment by CDDelta** [comment]
Both are not ready yet, was pending a release of the Ledger SDK from Zondax's side which just got updated, will get on this tomorrow. When the time comes this will have to be merged first.

**Comment by martonlederer** [comment]
Alright, thank you! Make sure to tag me when it's time

**Comment by CDDelta** [comment]
@martonlederer this PR is ready for your review. It conflicts with a change on `development` but I'm not sure which way to resolve it. What was the reasoning behind using `getUploader()` as opposed to `post()`?

**Comment by martonlederer** [comment]
@CDDelta I noticed that the network is more likely to drop txs when it's using "post". It even worked better for me, than fee multiplication

**Comment by CDDelta** [comment]
> @CDDelta I noticed that the network is more likely to drop txs when it's using "post". It even worked better for me, than fee multiplication

Interesting, resolved the merge conflicts with that and added a comment for it.

**Comment by martonlederer** [comment]
Thanks! No idea why that happens...

**Comment by heiningair** [comment]
Is this feature request still in the making? If not is there an estimate when this could work, since ledger nano s already integrates arweave?

**Pull request closed without merging**
