### PR TITLE
fix: resolve token & contact routes black screen

### PR DESCRIPTION
**Pull request by pawanpaudel93**
## Summary

This PR fixes the `Import Token` black screen issue.

### CODE REVIEW

**Comment by pawanpaudel93** [comment]
@7i7o @nicholaswma This seems to be the issue of matching both paths `/quick-settings/tokens/new` and `/quick-settings/tokens/:id` for `Import Token (/quick-settings/tokens/new)` and rendering both routes on top of each other.

Possible solutions:
1. As the PR
2. Rename the conflicting routes path so it only matches a single route for a path.

wdyt ?

**Comment by nicholaswma** [comment]
@pawanpaudel93 if possible I think renaming the path would be the better course so we don't encourage this type of pattern, but I'm okay with this solution for the time being

**Comment by pawanpaudel93** [comment]
@nicholaswma I used [Switch](https://github.com/molefrog/wouter/tree/v3?tab=readme-ov-file#switch-) now for those overlapping routes so only the first match is returned.

**Review by nicholaswma — APPROVED** [review]
tACK - works great! 🚀

**Review by 7i7o — APPROVED** [review]
tACK 👍 

Also agree with Nick that we should use non-overlapping routes in the future

**Pull request merged**
