### PR TITLE
Firefox

### PR DESCRIPTION
**Pull request by martonlederer**
This PR includes full support for Firefox, and firefox-based browsers.

A release can be submitted as soon as this is merged

### CODE REVIEW

**Review by t8 — APPROVED** [review]
LGTM. Amazing job @martonlederer!

**Comment by t8** [comment]
Now we just need to resolve merge conflicts from 0.2.6

**Comment by martonlederer** [comment]
Done @t8

**Comment by t8** [comment]
Ready to merge! I'll let you do the honors, @martonlederer.

**Pull request merged**
