### PR TITLE
feat: tests allowances state

### PR DESCRIPTION
**Pull request by arein**
Also:
* installs [jest](https://jestjs.io) as testing framework
* runs tests as part of build

### CODE REVIEW

**Review by t8 — CHANGES_REQUESTED** [review]
Thanks so much for the contribution, @arein! We use `yarn` instead of `npm`, so would you mind removing `package-lock.json` here?

**Comment by martonlederer** [comment]
Nice work :). Any chance you could creare a GitHub workflow for this?

**Comment by arein** [comment]
> Nice work :). Any chance you could creare a GitHub workflow for this?

It's already covered by the [.github/workflows/build.yml](build workflow) now that `yarn build` also runs the tests.

I think that's good for now. A dedicated workflow should also capture the test coverage but I think that warrants a dedicated Pull Request.

**Comment by martonlederer** [comment]
Hmm I guess you're right. Merging this now :)

**Pull request merged**
